import Head from 'next/head'
import Image from 'next/image'
import LoginBox from '../components/LoginBox'

export default function Home() {
  return (
    <div className="w-full h-screen flex flex-col justify-center items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='w-full flex justify-center'>
        <h1>Hello World</h1>
      </div>

      <LoginBox />

    </div>
  )
}
